In [1]:
import keras

C:\Users\shivanshu_dikshit\Anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('Churn_Modelling.csv')
X = data.iloc[:, 3:13].values
y = data.iloc[:, 13].values

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoderx1 = LabelEncoder()
X[:, 1] = labelencoderx1.fit_transform(X[:, 1])
labelencoderx2 = LabelEncoder()
X[:, 2] = labelencoderx2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [9]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [10]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [29]:
from keras.models import Sequential
from keras.layers import Dense

In [30]:
classifier = Sequential()

In [31]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [32]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [33]:
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [34]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [35]:
classifier.fit(X_train, Y_train, batch_size = 20, epochs = 200)

Epoch 1/200
8000/8000 [==============================] - 2s 227us/step - loss: 0.5515 - acc: 0.7939
Epoch 2/200
8000/8000 [==============================] - 1s 106us/step - loss: 0.4334 - acc: 0.7960
Epoch 3/200
8000/8000 [==============================] - 1s 106us/step - loss: 0.4291 - acc: 0.7960
Epoch 4/200
8000/8000 [==============================] - 1s 113us/step - loss: 0.4266 - acc: 0.7960
Epoch 5/200
8000/8000 [==============================] - 1s 124us/step - loss: 0.4237 - acc: 0.7960
Epoch 6/200
8000/8000 [==============================] - 1s 119us/step - loss: 0.4210 - acc: 0.7960
Epoch 7/200
8000/8000 [==============================] - 1s 111us/step - loss: 0.4187 - acc: 0.8132
Epoch 8/200
8000/8000 [==============================] - 1s 115us/step - loss: 0.4172 - acc: 0.8244
Epoch 9/200
8000/8000 [==============================] - 1s 119us/step - loss: 0.4157 - acc: 0.8278
Epoch 10/200
8000/8000 [==============================] - 1s 124us/step - loss: 0.4144 - acc: 0.8282

In [36]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [37]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [38]:
print (cm)

[[1503   92]
 [ 192  213]]


In [1]:
accuracy = (1503+213) / 2000

In [2]:
print(accuracy)

0.858
